# Generated by Django 5.1.1 on 2024-09-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('map_url', models.URLField(max_length=500)),
                ('img_url', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('has_sockets', models.BooleanField(default=False)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('can_take_calls', models.BooleanField(default=False)),
                ('seats', models.IntegerField()),
                ('coffee_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
