# Generated by Django 5.1.1 on 2024-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img_url',
            field=models.URLField(max_length=5005),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='place',
            name='map_url',
            field=models.URLField(max_length=5005),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=2555),
        ),
    ]
