# Generated by Django 5.1 on 2024-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlet', '0004_alter_place_coffee_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='test',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
